natloc_or_national = {
"Cartoon Network": "Natloc",
"AMC": "National",
"BabyFirst TV": "National",
"BET Jams": "National",
"BETSOUL": "National",
"BET Her": "National",
"Bravo": "Natloc",
"E!": "National",
"Freeform": "National",
"HLN": "National",
"CNN":"National",
"IFC": "National",
"Laff TV": "National",
"MSNBC": "Natloc",
"MTV2": "National",
"NEWSY": "National",
"National Geographic": "National",
"NEWSMAX": "National",
"Ovation TV": "Natloc",
"Oxygen": "Natloc",
"QUBO": "National",
"REELZChannel": "National",
"Revolt": "National",
"truTV": "National",
"USA Network": "National",
"VH1": "National",
"VICELAND": "National",
"WE tv": "National",
"Crime + Investigation": "National",
"Family Entertainment Television": "National",
"Fuse TV": "National",
"Galavision Cable Network": "National",
"Hallmark Channel": "National",
"Hallmark Drama": "National",
"Hallmark Movies & Mysteries": "National",
"Investigation Discovery": "Natloc",
"Lifetime Real Women": "National",
"Ovation TV": "National",
"Tr3s: MTV": "National",
"Universal Kids": "National",
}
